POST http://localhost:7071/api/PublishEvent/triggers/manual/invoke?api-version=2022-05-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=SS8qldJRkWWWx7sonCeNEIfu-Ju-GqfbYYZDEdWhXtY HTTP/1.1
Content-Type: application/json

{
    "messageid": "abc123",
    "operation": "OtherEvent",
    "message":
    {
        "orderid": 1234,
        "total": 200.00
    }
}